import { useEffect, useState } from "react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import {
  AppShell,
  NavLink,
  Burger,
  Center,
  Footer,
  Header,
  Navbar,
  MediaQuery,
  Stack,
  Text,
  useMantineTheme,
  Button,
} from "@mantine/core";

import {
  IconAdjustmentsAlt,
  IconActivity,
  IconLogout,
  IconBoxMultiple,
  IconSocial,
} from "@tabler/icons";

import { getCookieAsObject, removeCookie } from "../../utils/utils";

export default function AppShellLayout({
  children,
}: {
  children: JSX.Element;
}) {
  const router = useRouter();
  const theme = useMantineTheme();
  const [opened, setOpened] = useState(false);
  const [token, setToken] = useState<string | undefined>(undefined);

  useEffect(() => {
    const _token = getCookieAsObject().token;
    setToken(_token);
    if (_token === "" || !_token) router.push("/login");
  }, [setToken, router]);
  return (
    <>
      <Head>
        <title>Premier Creators</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppShell
        styles={{
          main: {
            background:
              theme.colorScheme === "dark"
                ? theme.colors.dark[8]
                : theme.colors.gray[0],
          },
        }}
        navbarOffsetBreakpoint="sm"
        asideOffsetBreakpoint="sm"
        navbar={
          <Navbar
            p="md"
            hiddenBreakpoint="sm"
            hidden={!opened}
            width={{ sm: 200, lg: 300 }}
          >
            <Stack>
              {/* <Link href={"/app/activity"} style={{ textDecoration: "none" }}>
                <NavLink icon={<IconActivity />} label={"Activity"} />
              </Link> */}
              <Link
                href={"/app/credentials-manager"}
                style={{ textDecoration: "none" }}
              >
                <NavLink
                  icon={<IconAdjustmentsAlt />}
                  label={"Credentials Manager"}
                />
              </Link>
              <Link
                href={"/app/subreddit-manager"}
                style={{ textDecoration: "none" }}
              >
                <NavLink icon={<IconSocial />} label={"Subreddit Manager"} />
              </Link>
              <Link href={"/app/submissions"} style={{ textDecoration: "none" }}>
                <NavLink icon={<IconBoxMultiple />} label={"Submissions"} />
              </Link>
              <br />
              <br />
              <br />
              <Button
                leftIcon={<IconLogout />}
                variant="filled"
                onClick={(e) => {
                  e.preventDefault();
                  removeCookie("token");
                  router.reload();
                }}
              >
                Sign Out
              </Button>
            </Stack>
          </Navbar>
        }
        footer={
          <Footer height={60} p="md">
            <Center>
              Copyright © 2023 Premier Creators. All rights reserved.
            </Center>
          </Footer>
        }
        header={
          <Header height={{ base: 50, md: 70 }} p="md">
            <div
              style={{ display: "flex", alignItems: "center", height: "100%" }}
            >
              <MediaQuery largerThan="sm" styles={{ display: "none" }}>
                <Burger
                  opened={opened}
                  onClick={() => setOpened((o) => !o)}
                  size="sm"
                  color={theme.colors.gray[6]}
                  mr="xl"
                />
              </MediaQuery>

              <Text fw={700} fz="lg">
                Premier Creators
              </Text>
            </div>
          </Header>
        }
      >
        {children}
      </AppShell>
    </>
  );
}
