import Head from "next/head";
import { useRouter } from "next/router";
import { useForm } from "@mantine/form";
import { Center, TextInput, Button, Group, Code, Grid } from "@mantine/core";
import { showNotification } from "@mantine/notifications";

import login from "../api/login";

const LoginForm = () => {
  const router = useRouter();
  const form = useForm({
    initialValues: {
      username: "",
      password: "",
    },
  });
  return (
    <>
      <Head>
        <title>Premier Creators Portal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          width: "40vw",
          marginTop: "auto",
          marginBottom: "auto",
          marginLeft: "0",
          marginRight: "0",
        }}
      >
        <TextInput
          label="Username"
          placeholder="Your username"
          {...form.getInputProps("username")}
        />
        <TextInput
          mt="md"
          label="Password"
          placeholder="Your password"
          type={"password"}
          {...form.getInputProps("password")}
        />

        <Group position="center" mt="xl">
          <Button
            variant="filled"
            onClick={() =>
              login(form.values.username, form.values.password).then(
                (response) => {
                  if (response.data.status === "SUCCESSFUL") {
                    document.cookie = `token=${response.data.data.token}`;
                    router.push("/app/credentials-manager");
                  } else if (response.data.status === "UNSUCCESSFUL") {
                    console.log(response.data);
                    return showNotification({
                      title: "Error",
                      message: response.data.data.message,
                      color: "red",
                    });
                  }
                }
              )
            }
          >
            Login
          </Button>
        </Group>
      </main>
    </>
  );
};

export default function LoginPage() {
  return (
    <Grid grow sx={{ width: "100vw", height: "100vh" }}>
      <Grid.Col span={12}>
        <Center sx={{ width: "100%", height: "100%" }}>
          <h1>Premier Creators</h1>
        </Center>
      </Grid.Col>
      <Grid.Col span={12}>
        <Center sx={{ width: "100%", height: "100%" }}>
          <LoginForm />
        </Center>
      </Grid.Col>
      <Grid.Col span={12}>
        <Center sx={{ width: "100%", height: "100%" }}>
          <Code>Copyright © 2022 Premier Creators. All rights reserved.</Code>
        </Center>
      </Grid.Col>
    </Grid>
  );
}
